# general configuration
url: https://pocketninja.dev
baseurl: ''
author: 'Pocket Ninja'
description: 'Home of Pocket Apps LLC'
copyright: 'Pocket Apps LLC'
logo: "/assets/logo.png"

# Assets
sass:
  sass_dir: css
  style: compressed
  sourcemap: never

# exclude
exclude: ["Gemfile", "Gemfile.lock", "README.md"]

# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Routing
include:
  - _redirects
