# general configuration
url: https://pocketninja.dev
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logo.png"
  # author will appear under the avatar (optional)
  author: "Pocket Ninja"
  # tagline will appear under the title (optional)
  tagline: "Silently killing with awesome apps"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "pocketninjadev"


# Assets
sass:
  sass_dir: css
  style: compressed
  sourcemap: never

# exclude
exclude: ["Gemfile", "Gemfile.lock", "README.md"]

# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Routing
include:
  - _redirects
